### PR TITLE
add basic auth support

### PR DESCRIPTION
**Pull request by byxorna**
Adds support for Streams protected by basic auth.

### CODE REVIEW

**Comment by donovanhide** [comment]
Worth adding BasicAuth support for the server side as well?

**Comment by byxorna** [comment]
@donovanhide it was outside of the scope of my needs. I am using `eventsource` as a client library only to consume an SSE stream from https://github.com/tumblr/collins, so this PR was quick and dirty. :)

**Comment by donovanhide** [comment]
Fair enough :-)

Is it worth thinking about a different function signature:
```
func SubscribeFromRequest(url, lastEventId string, req *http.Request)
```
so the user can manually set any headers they want for different types of authorisation or anything else?

**Comment by byxorna** [comment]
@donovanhide Sure. That seems most extensible and future-proof, for sure. It will complicate the PR a bit, but ill have an update in a few min.

**Comment by byxorna** [comment]
@donovanhide updated.

**Comment by donovanhide** [comment]
Looks good! Thanks!

**Pull request merged**
